package application;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.stage.Stage;

public class abtpageController {

	    @FXML
	    private Button button_billnew;

	    @FXML
	    private Button button_logout;

	    @FXML
	    private Button button_menu;
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
	
    @FXML
	public void onclick_menu(ActionEvent event) throws IOException {
//		TODO Autogenerated
		Parent submit_parent = FXMLLoader.load(getClass().getResource("cartpage.fxml"));
		Scene submit_scene = new Scene(submit_parent);
		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		app_stage.setScene(submit_scene);
		app_stage.show();
    
}
    
    @FXML
	public void onclick_billnew(ActionEvent event) throws IOException {
//		TODO Autogenerated
//		Parent submit_parent = FXMLLoader.load(getClass().getResource("billpage.fxml"));
//		Scene submit_scene = new Scene(submit_parent);
//		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
//		app_stage.setScene(submit_scene);
//		app_stage.show();
    	
    	System.out.println("Place order first!");
		Alert alert = new Alert(Alert.AlertType.ERROR);
		alert.setContentText("First Place the order from Menu");
		alert.show();
    
}
    
    @FXML
	public void onclick_logout(ActionEvent event) throws IOException {
//		TODO Autogenerated
		Parent submit_parent = FXMLLoader.load(getClass().getResource("loginpage.fxml"));
		Scene submit_scene = new Scene(submit_parent);
		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		app_stage.setScene(submit_scene);
		app_stage.show();
    
}
    
   
}
