package application;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class loginpageController implements Initializable{
	

    @FXML
    private Button button_login;

//    @FXML
//    private TextField txf_city;
    
    @FXML
    private Button button_regatlog;

    @FXML
    private PasswordField txf_passw;

    @FXML
    private TextField txf_usern;

	protected Object DBUtils;

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
	
	//	button_login.setOnAction(new EventHandler<ActionEvent>() {
			
		//	@Override
			//public void handle(ActionEvent event) {
				//DBUtils db= new DBUtils();
				
				 //db.logInUser(event, "pagenew.fxml", "log in!");
					
			//}
			
			
	//	});
		
	}
	@FXML
	void setOnAction(ActionEvent event) {
		try {
		System.out.println("Okay");
		DBUtils db=new DBUtils();
		 db.logInUser(event, txf_usern.getText(), txf_passw.getText());
	}catch(Exception e) {
		System.out.println("No "+ e.getMessage());
}
	}
	
	 @FXML
		public void onclick_regatlog(ActionEvent event) throws IOException {
//			TODO Autogenerated
			Parent submit_parent = FXMLLoader.load(getClass().getResource("signpage.fxml"));
			Scene submit_scene = new Scene(submit_parent);
			Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
			app_stage.setScene(submit_scene);
			app_stage.show();
	    }
	
}