package application;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class signpageController {

    @FXML
    private TextField city;

    @FXML
    private TextField customername;

    @FXML
    private PasswordField passw;

    @FXML
    private TextField phoneno;

    @FXML
    private Button register;

    @FXML
    private TextField usern;
    
    @FXML
    private Button button_log;
    
    
    
  //  Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    @FXML
	public void onclick(ActionEvent event) throws IOException {
//		TODO Autogenerated
		Parent submit_parent = FXMLLoader.load(getClass().getResource("loginpage.fxml"));
		Scene submit_scene = new Scene(submit_parent);
		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		app_stage.setScene(submit_scene);
		app_stage.show();
		
		
		System.out.println(city.getText());
		System.out.println(customername.getText());
	    System.out.println(passw.getText());
	    System.out.println(phoneno.getText());
	    System.out.println(register.getText());
	    System.out.println(usern.getText());

	   newuser.newuserDatabase(usern.getText(),passw.getText(), customername.getText(),phoneno.getText(),city.getText());

//usern.getText(), passw.getText(), customername.getText(), phoneno.getText(), city.getText(), register.getText()
    }
    
    @FXML
   	public void onclick1(ActionEvent event) throws IOException {
//   		TODO Autogenerated
   		Parent submit_parent = FXMLLoader.load(getClass().getResource("loginpage.fxml"));
   		Scene submit_scene = new Scene(submit_parent);
   		Stage app_stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
   		app_stage.setScene(submit_scene);
   		app_stage.show();
    }
}